#!/bin/sh
## Assume standard 6 px gap

cd "$(dirname $0)"
for i in */in*; do
	size="$(dirname "$i")"
	in="$(binpack -x "${size%x*}" -y "${size#*x}" -g 6 < "$i")"
	echo "$in"
	#grep "$in" "$size/out${i#*in*}" >/dev/null && echo "Test $size - ${i#*in*} success"
done